# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-09-19 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=4096),
        ),
    ]
